// pages/web/About.jsx
import { useEffect } from 'react';
import { gsap } from 'gsap';

const About = () => {
  useEffect(() => {
    gsap.from('.fade-in', {
      opacity: 0,
      y: 30,
      duration: 0.6,
      stagger: 0.15,
      ease: 'power3.out',
    });
  }, []);

  return (
    <div className="bg-white min-h-screen py-20 px-4">
      <div className="max-w-6xl mx-auto text-center mb-16">
        <h1 className="text-4xl font-bold text-gray-900 mb-4 fade-in">About VisualStock</h1>
        <p className="text-gray-600 text-lg fade-in">
          Revolutionizing stock photography with the power of AI. Explore stunning, original visuals generated by next-gen technology.
        </p>
      </div>

      <div className="max-w-5xl mx-auto grid md:grid-cols-2 gap-12 items-center">
        <div className="space-y-6 fade-in">
          <h2 className="text-2xl font-semibold text-gray-800">Who We Are</h2>
          <p className="text-gray-600 leading-relaxed">
            VisualStock is a modern stock image platform offering **AI-generated photos** for creators, marketers,
            and digital businesses. We use cutting-edge generative AI to craft images that are unique, versatile,
            and free from traditional licensing limitations.
          </p>
          <p className="text-gray-600 leading-relaxed">
            From abstract concepts to realistic scenes, we cover a wide range of styles and categories — giving you endless visual possibilities for your projects.
          </p>
        </div>

        <div className="fade-in">
          <img
            src="https://source.unsplash.com/800x600/?ai,technology,art"
            alt="AI creativity"
            className="rounded-xl shadow-lg w-full h-auto object-cover"
          />
        </div>
      </div>

      <div className="max-w-5xl mx-auto mt-20 fade-in">
        <h2 className="text-2xl font-semibold text-gray-800 text-center mb-8">What Makes Us Different</h2>
        <div className="grid md:grid-cols-3 gap-8 text-center">
          <div className="p-6 border rounded-xl shadow-sm hover:shadow-md transition">
            <h3 className="text-xl font-bold text-indigo-600 mb-2">AI-Powered Content</h3>
            <p className="text-gray-600 text-sm">All our images are generated using state-of-the-art AI tools — ensuring originality, flexibility, and creative control.</p>
          </div>
          <div className="p-6 border rounded-xl shadow-sm hover:shadow-md transition">
            <h3 className="text-xl font-bold text-indigo-600 mb-2">Limitless Variety</h3>
            <p className="text-gray-600 text-sm">Need a futuristic city, magical forest, or abstract design? We create visuals that traditional stock platforms can't offer.</p>
          </div>
          <div className="p-6 border rounded-xl shadow-sm hover:shadow-md transition">
            <h3 className="text-xl font-bold text-indigo-600 mb-2">Fast & Affordable</h3>
            <p className="text-gray-600 text-sm">High-quality visuals available on demand — no costly photo shoots, no licensing headaches.</p>
          </div>
        </div>
      </div>

      <div className="max-w-4xl mx-auto mt-24 text-center fade-in">
        <h2 className="text-2xl font-semibold text-gray-800 mb-4">Work with Us</h2>
        <p className="text-gray-600 mb-6">
          Whether you're a brand, designer, or platform looking for unique visuals, we're here to support your vision.
          Contact us to discuss custom image requests, bulk licensing, or collaborations.
        </p>
        <a
          href="/contact"
          className="inline-block px-6 py-3 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition"
        >
          Contact Us
        </a>
      </div>
    </div>
  );
};

export default About;
